name: Deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - feat/data-provider-refactor-back

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Set mode + destination
        id: set-mode
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "vite_mode=production" >> $GITHUB_OUTPUT
            echo "dest=." >> $GITHUB_OUTPUT
          else
            echo "vite_mode=staging" >> $GITHUB_OUTPUT
            echo "dest=preview" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build -- --mode ${{ steps.set-mode.outputs.vite_mode }}
        env:
          VITE_MAPBOX_TOKEN: ${{ secrets.VITE_MAPBOX_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          destination_dir: ${{ steps.set-mode.outputs.dest }}
